services:
  databricks-local:
    build: .
    container_name: databricks-local
    ports:
      - "8888:8888"
      - "4040:4040"
      - "5050:5050"
    volumes:
      - ./notebooks:/home/jovyan/work
    environment:
      - GRANT_SUDO=yes
      - JUPYTER_ENABLE_LAB=yes
    command: start-notebook.sh
